### ISSUE TITLE
Extensions disabled by Chrome

### ISSUE THREAD

**Issue by Germey** [2293736867/Github1sExtension#1]
This extension is not listed in the Chrome Web Store and may have been added without your knowledge. Learn more

**Comment by Germey** [comment]
Nice Extension, Thanks!

Suggest upload it to Chrome Web Store for better experience. 

![](https://qiniu.cuiqingcai.com/xk3u5.png)

**Comment by gkdgkdgkdgkd** [comment]
Now you can use the official website called "github.dev".
